export enum Actions {
  SET_TIME = "SET_TIME",
  START_TIMER = "START_TIMER",
  STOP_TIMER = "STOP_TIMER",
  COUNT_DOWN_ONE_SECOND = "COUNT_DOWN_ONE_SECOND",
  COUNT_DOWN_FINISHED = "COUNT_DOWN_FINISHED",
  ADD_NOTIFICATION = "ADD_NOTIFICATION"
}
